# Generated by Django 3.2.11 on 2022-01-17 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('host', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(max_length=100)),
                ('num_bedrooms', models.IntegerField()),
                ('max_guests', models.IntegerField()),
                ('type_of', models.CharField(choices=[('Daily', 'Daily'), ('Monthly', 'Monthly')], max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('host_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='host.host')),
            ],
        ),
    ]
